
### Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 

### Needed to make tmux work with bashrc when RVM is installed
. ~/.bashrc
. ~/.profile
