###
##
# .bash_profile: sourced by /etc/bashrc for login (non-interactive) shells.

# stop parent xtrace (debug)
set +x

# debug
#set -x;printf 'DEBUG: %s\n' "$_ -$- $*"

# return to parent process if BASH is interactive (tty attached), unless this
# is OS X in which case source the interactive runcom (.bashrc)
if [[ "$(uname)" == "Darwin" ]];then
	source ~/.bashrc
else 
	[[ $- == *i* ]] && return
fi

# stop xtrace (debug)
set +x

